// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ENIConfig struct {
	ApiVersion *string        `pulumi:"apiVersion"`
	Kind       *string        `pulumi:"kind"`
	Spec       *ENIConfigSpec `pulumi:"spec"`
}

type ENIConfigSpec struct {
	SecurityGroups []string `pulumi:"securityGroups"`
	Subnet         *string  `pulumi:"subnet"`
}

type ENIConfigSpecOutput struct{ *pulumi.OutputState }

func (ENIConfigSpecOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ENIConfigSpec)(nil)).Elem()
}

func (o ENIConfigSpecOutput) ToENIConfigSpecOutput() ENIConfigSpecOutput {
	return o
}

func (o ENIConfigSpecOutput) ToENIConfigSpecOutputWithContext(ctx context.Context) ENIConfigSpecOutput {
	return o
}

func (o ENIConfigSpecOutput) SecurityGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ENIConfigSpec) []string { return v.SecurityGroups }).(pulumi.StringArrayOutput)
}

func (o ENIConfigSpecOutput) Subnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ENIConfigSpec) *string { return v.Subnet }).(pulumi.StringPtrOutput)
}

type ENIConfigSpecMapOutput struct{ *pulumi.OutputState }

func (ENIConfigSpecMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ENIConfigSpec)(nil)).Elem()
}

func (o ENIConfigSpecMapOutput) ToENIConfigSpecMapOutput() ENIConfigSpecMapOutput {
	return o
}

func (o ENIConfigSpecMapOutput) ToENIConfigSpecMapOutputWithContext(ctx context.Context) ENIConfigSpecMapOutput {
	return o
}

func (o ENIConfigSpecMapOutput) MapIndex(k pulumi.StringInput) ENIConfigSpecOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ENIConfigSpec {
		return vs[0].(map[string]ENIConfigSpec)[vs[1].(string)]
	}).(ENIConfigSpecOutput)
}

func init() {
	pulumi.RegisterOutputType(ENIConfigSpecOutput{})
	pulumi.RegisterOutputType(ENIConfigSpecMapOutput{})
}
