# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .replicated_bucket import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_aws_s3_replicated_bucket.crd_k8s_amazonaws_com as __crd_k8s_amazonaws_com
    crd_k8s_amazonaws_com = __crd_k8s_amazonaws_com
else:
    crd_k8s_amazonaws_com = _utilities.lazy_import('pulumi_aws_s3_replicated_bucket.crd_k8s_amazonaws_com')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aws-s3-replicated-bucket",
  "mod": "index",
  "fqn": "pulumi_aws_s3_replicated_bucket",
  "classes": {
   "aws-s3-replicated-bucket:index:ReplicatedBucket": "ReplicatedBucket"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aws-s3-replicated-bucket",
  "token": "pulumi:providers:aws-s3-replicated-bucket",
  "fqn": "pulumi_aws_s3_replicated_bucket",
  "class": "Provider"
 }
]
"""
)
