// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Gcp/gke.Outputs
{

    [OutputType]
    public sealed class NodePoolAutoscaling
    {
        /// <summary>
        /// Location policy used when scaling up a nodepool.
        /// </summary>
        public readonly Pulumi.Google-native.Container/v1.NodePoolAutoscalingLocationPolicy? LocationPolicy;

        [OutputConstructor]
        private NodePoolAutoscaling(Pulumi.Google-native.Container/v1.NodePoolAutoscalingLocationPolicy? locationPolicy)
        {
            LocationPolicy = locationPolicy;
        }
    }
}
