// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export namespace gcp {
    export namespace gke {
        export interface NodePoolAutoscaling {
            /**
             * Location policy used when scaling up a nodepool.
             */
            locationPolicy?: enums.container.v1.NodePoolAutoscalingLocationPolicy;
        }

    }
}
