// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { ReplicatedBucketArgs } from "./replicatedBucket";
export type ReplicatedBucket = import("./replicatedBucket").ReplicatedBucket;
export const ReplicatedBucket: typeof import("./replicatedBucket").ReplicatedBucket = null as any;
utilities.lazyLoad(exports, ["ReplicatedBucket"], () => require("./replicatedBucket"));


// Export sub-modules:
import * as types from "./types";

export {
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "aws-s3-replicated-bucket:index:ReplicatedBucket":
                return new ReplicatedBucket(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("aws-s3-replicated-bucket", "index", _module)
pulumi.runtime.registerResourcePackage("aws-s3-replicated-bucket", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:aws-s3-replicated-bucket") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
