// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

import * as pulumiAws from "@pulumi/aws";

export class ReplicatedBucket extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'aws-s3-replicated-bucket:index:ReplicatedBucket';

    /**
     * Returns true if the given object is an instance of ReplicatedBucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ReplicatedBucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ReplicatedBucket.__pulumiType;
    }

    /**
     * Bucket to which data should be replicated.
     */
    public /*out*/ readonly destinationBucket!: pulumi.Output<pulumiAws.s3.Bucket>;
    /**
     * test stuff
     */
    public /*out*/ readonly eniConfig!: pulumi.Output<{[key: string]: outputs.crd.k8s.amazonaws.com.v1alpha1.ENIConfigSpec} | undefined>;
    /**
     * Bucket to which objects are written.
     */
    public /*out*/ readonly sourceBucket!: pulumi.Output<pulumiAws.s3.Bucket>;

    /**
     * Create a ReplicatedBucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ReplicatedBucketArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.destinationRegion === undefined) && !opts.urn) {
                throw new Error("Missing required property 'destinationRegion'");
            }
            resourceInputs["destinationRegion"] = args ? args.destinationRegion : undefined;
            resourceInputs["destinationBucket"] = undefined /*out*/;
            resourceInputs["eniConfig"] = undefined /*out*/;
            resourceInputs["sourceBucket"] = undefined /*out*/;
        } else {
            resourceInputs["destinationBucket"] = undefined /*out*/;
            resourceInputs["eniConfig"] = undefined /*out*/;
            resourceInputs["sourceBucket"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ReplicatedBucket.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ReplicatedBucket resource.
 */
export interface ReplicatedBucketArgs {
    /**
     * Region to which data should be replicated.
     */
    destinationRegion: pulumi.Input<string>;
}
